kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: app01
  namespace: tjpe-homologacao-ume
  finalizers:
    - kubernetes.io/pvc-protection
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  storageClassName: nfs
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: app01
  namespace: tjpe-homologacao-ume
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app01
      namespace: tjpe-homologacao-ume
  template:
    metadata:
      labels:
        app: app01
        namespace: tjpe-homologacao-ume
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /volume
              name: app01
      volumes:
        - name: app01
          persistentVolumeClaim:
            claimName: app01
---
apiVersion: v1
kind: Service
metadata:
  name: app01
  namespace: tjpe-homologacao-ume
spec:
  selector:
    app: app01
    namespace: tjpe-homologacao-ume
  ports:
    - port: 80
      targetPort: 80
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app01
  namespace: tjpe-homologacao-ume
data:
  ambiente: producao
  app_name: nginx-deployment-01
  porta_padrao: "80"
  mensagem_boas_vindas: "Bem-vindo ao nginx no Kubernetes UPDATE!"
