apiVersion: apps/v1
kind: Deployment
metadata:
  name: tjpe-homologacao-ume
  namespace: tjpe-producao-gedai
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tjpe-homologacao-ume
  template:
    metadata:
      labels:
        app: tjpe-homologacao-ume
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: tjpe-homologacao-ume
  namespace: tjpe-producao-gedai
spec:
  selector:
    app: tjpe-homologacao-ume
  ports:
    - port: 80
      targetPort: 80